### ISSUE TITLE
Can't get scrubby installed with conda

### ISSUE THREAD

**Issue by gokeson** [esteinig/scrubby#22]
PackagesNotFoundError: The following packages are not available from current channels:

  - scrubby

**Comment by ammaraziz** [comment]
@gokeson use the alternative install method:

```
mamba install -c conda-forge rust
cargo install scrubby
```

FYI @esteinig I'm working with a colleague on a chlamdya pipeline which uses `scrubby` to remove human reads.

**Comment by esteinig** [comment]
@gokeson @ammaraziz - apologies, this is mostly been released as "under development" (should make some time to update the package at some point, it's been useful for our metagenomics work)

You might want to check out the `empty` branch if using this in a pipeline - it implements an empty file guard which can sometimes cause failures when  inputs are empty or reads are completely depleted (e.g. in negative template controls)

Otherwise there is also `Hostile` from the Derrick Crook and colleagues that looks really good

**Comment by gokeson** [comment]
Thanks for the explanation @esteinig. It is working well in my hands right now. Thanks again.

**Comment by ammaraziz** [comment]
Thanks @esteinig we like `scrubby` because it does both depletion and classification :)
